# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
  - docker pull mysql:8
  - docker run --name test-mysql-8 --rm -e MYSQL_ROOT_PASSWORD=test-pw -v $PWD/.test/mysql/:/docker-entrypoint-initdb.d/ -p 33306:3306 -d mysql:8

after_script:
  - docker stop test-mysql-8
  - ./ee setup clean
  - rm .env

#
# EENV Core: ldap, keycloak, web, elexis-server
#
core: 
  stage: test
  script:
    - cp .test/.env.core .env
    - source .env
    - ./ee system cmd pull -q # while mysql starts up
    - sleep 10
    - ./ee setup configure
    - echo "startup elexis-environment" #TODO
    - ./ee setup runtest
