# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
  - docker pull mysql:8
  - docker pull medevit/eenv-config

after_script:
  - ./ee system cmd stop
  - ./ee system cmd rm -f
  - docker volume prune -f
  - docker stop test-mysql-8
  - ./ee setup clean
  - rm .env

stages:
  - testCore
  - testFull

#
# Elexis-Environment core only: ldap, keycloak, web, elexis-server
#
core: 
  stage: testCore
  script:
    - cp .test/.env.core .env # copy test environment configuration
    - source .env 
    - ./ee setup mysql_init_code > .test/init.sql # prepare mysql init code for mysql startup
    - docker run --name test-mysql-8 --rm -e MYSQL_ROOT_PASSWORD=test-pw -v $PWD/.test/init.sql:/docker-entrypoint-initdb.d/init.sql:ro -p 33306:3306 -d mysql:8
    - ./ee system cmd pull -q # while mysql starts up pull required images
    - sleep 15 # wait for mysql - lame solution
    - ./ee setup configure # prepare setup and generate self-signed-cert next
    - openssl req -x509 -newkey rsa:2048 -keyout ./site/certificate.key -out ./site/certificate.crt -days 365 -nodes -subj "/CN=localhost"
    - ./ee system cmd up -d # start the elexis-environment
    - .test/wait_for_http_200_es.sh # wait for elexis-server to become ready
    - ./ee system cmd ps # print the status of the elexis-environment containers
    - ./ee setup runtest # run the core runtest

#
# Elexis-Environment all-modules-enabled
#
full:
  stage: testFull
  script:
    - cp .test/.env.full .env
    - source .env
    - ./ee setup mysql_init_code > .test/init.sql
    - docker run --name test-mysql-8 --rm -e MYSQL_ROOT_PASSWORD=test-pw -v $PWD/.test/init.sql:/docker-entrypoint-initdb.d/init.sql:ro -p 33306:3306 -d mysql:8
    - ./ee system cmd pull -q # while mysql starts up
    - sleep 15 # wait for mysql - lame solution
    - ./ee setup configure # prepare setup and generate self-signed-cert next
    - openssl req -x509 -newkey rsa:2048 -keyout ./site/certificate.key -out ./site/certificate.crt -days 365 -nodes -subj "/CN=localhost"
    - ./ee system cmd up -d
    - .test/wait_for_http_200_rocketchat.sh
    - ./ee system cmd ps
    - ./ee setup runtest