# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
  - docker pull mysql:8
  - docker run --name test-mysql-8 --rm -e MYSQL_ROOT_PASSWORD=test-pw -v $PWD/.test/mysql/:/docker-entrypoint-initdb.d/ -p 33306:3306 -d mysql:8

after_script:
  - docker stop test-mysql-8
  - ./ee system cmd stop
  - ./ee setup clean
  - ./ee system cmd rm -f
  - docker volume prune -f
  - rm .env

#
# EENV Core: ldap, keycloak, web, elexis-server
#
core: 
  stage: test
  script:
    - cp .test/.env.core .env
    - source .env
    - ./ee system cmd pull -q # while mysql starts up
    - sleep 15 # wait for mysql - lame solution
    - ./ee setup configure
    - ./ee system cmd up -d
    - .test/wait_for_http_200_es.sh https://${EE_HOSTNAME}/services/swagger.json
    - ./ee setup runtest
