version: '3'

services:

  ee-config:
    build: ../ee-util
    command: /ee_start_setup.sh
    depends_on:
        - keycloak
    environment:
      - EE_HOSTNAME
      - ADMIN_PASSWORD
      - ORGANISATION_NAME
      - ORGANSATION_DOMAIN
      - ORGANISATION_BASE_DN
      - RDBMS_ELEXIS_USERNAME
      - RDBMS_ELEXIS_DATABASE
      - RDBMS_ELEXIS_PASSWORD
      - RDBMS_HOST
      - RDBMS_PORT
      - ENABLE_ROCKETCHAT
      - ENABLE_BOOKSTACK
      - ENABLE_NEXTCLOUD