version: '3'

services:

  elexis-server:
    image: medevit/elexis-server:latest
    volumes:
      - elexis-server_home:/elexis
    environment:
      - DB_TYPE=$RDBMS_TYPE
      - DB_HOST=$RDBMS_HOST:$RDBMS_PORT
      - DB_DATABASE=$RDBMS_ELEXIS_DATABASE
      - DB_USERNAME=$RDBMS_ELEXIS_USERNAME
      - DB_PASSWORD=$RDBMS_ELEXIS_PASSWORD
      - DB_JDBC_PARAMETER_STRING=$RDBMS_ELEXIS_JDBC_PARAMETER_STRING
      - EE_HOSTNAME
      - ORGANISATION_NAME
      - REDMINE_APIKEY
    expose:
      - 8380
    networks:
      - backend
    ports:
      - "7234:7234"
    extra_hosts:
      - ${EE_HOSTNAME}:${EE_HOST_INTERNAL_IP}
    logging:  
      driver: json-file
      options:
          max-size: "2M"
          max-file: "10"

volumes:
  elexis-server_home: