version: '3'

services:

  # api-php
  elexis-web-api-php:
    image: gitlab.medelexis.ch:4567/elexis-web/web-docker/api:develop
    volumes:
      - elexis-web-api_php:/www
    depends_on:
      - keycloak
      - elexis-server
    networks:
      - backend
    environment:
      - APP_NAME="Lumen"
      - APP_ENV="local"
      - APP_DEBUG=true
      - APP_URL=https://$EE_HOSTNAME/api/elexisweb/
      - FORCE_HTTPS=true
      - FHIR_API_URL=https://$EE_HOSTNAME/fhir
      - DB_CONNECTION="mysql"
      - DB_HOST=$RDBMS_HOST
      - DB_PORT=$RDBMS_PORT
      - DB_DATABASE=$RDBMS_ELEXISWEB_DATABASE
      - DB_USERNAME=$RDBMS_ELEXISWEB_USERNAME
      - DB_PASSWORD=$RDBMS_ELEXISWEB_PASSWORD
      - OIDC_DUMP_USER_DETAILS=false
      - OIDC_CLIENT_ID=elexis-web-api
      - OIDC_ISSUER=https://$EE_HOSTNAME/keycloak/auth/realms/ElexisEnvironment
      - OIDC_AUTH_ENDPOINT=https://$EE_HOSTNAME/keycloak/auth/realms/ElexisEnvironment/protocol/openid-connect/auth
      - OIDC_TOKEN_ENDPOINT=https://$EE_HOSTNAME/keycloak/auth/realms/ElexisEnvironment/protocol/openid-connect/token
      - OIDC_LOGOUT_ENDPOINT=https://$EE_HOSTNAME/keycloak/auth/realms/ElexisEnvironment/protocol/openid-connect/logout
      - OID_LOGIN_SUCCESS_URL=https://$EE_HOSTNAME/elexisweb/ # fallback to referrer url
      - OID_LOGIN_ERROR_URL=https://$EE_HOSTNAME/elexisweb/error
      - OIDC_AUTO_REFRESH_TOKEN=true
      - AUTH_METHOD=oidc
      - OIDC_CLIENT_SECRET=$X_EE_ELEXIS_WEB_API_CLIENT_SECRET
      - OIDC_PUBLIC_KEY=jwt-key.key


  # websockets
  elexis-web-websockets:
    image: gitlab.medelexis.ch:4567/elexis-web/web-docker/api:develop
    volumes:
      - elexis-web-api_php:/www
    entrypoint: php artisan websockets:serve
    restart: always
    expose:
      - 6001
    networks:
      - backend
    environment:
      - BROADCAST_DRIVER=pusher
      - PUSHER_APP_ID=local
      - PUSHER_APP_KEY=local
      - PUSHER_APP_SECRET=local
      - PUSHER_APP_HOST_NAME=elexis-web-websockets
    depends_on:
      - elexis-web-api-php

  # api-nginx
  elexis-web-api-nginx:
    image: nginx:1.20-alpine
    depends_on:
      - elexis-web-api-php
    working_dir: /www
    expose:
      - 3005
    volumes:
      - elexis-web-api_php:/www
      - ./assets/elexisweb/etc/nginx:/etc/nginx/conf.d:ro
    networks:
      - backend

  # app
  elexis-web-app:
    image: gitlab.medelexis.ch:4567/elexis-web/web-docker/app:develop
    expose: 
      - 3004
    networks:
      - backend
    environment:
      - REACT_APP_API_FHIR_URL=https://$EE_HOSTNAME/api/elexisweb/fhir/
      - REACT_APP_API_URL=https://$EE_HOSTNAME/api/elexisweb/
      - REACT_APP_TITLE=Elexis-Web
      - PUBLIC_URL=/elexisweb/
      - REACT_APP_AXIOS_LOG=true
      - REACT_APP_PUSHER_APP_KEY=local
      - REACT_APP_PUSHER_APP_WSPATH=api/elexisweb-socket
      - REACT_APP_PUSHER_APP_WSPORT=80
      - REACT_APP_PUSHER_APP_WSPORT=443
      #######
      - JEST_HEADLESS=true
      - REACT_APP_SITE_URL=https://$EE_HOSTNAME
      - JEST_API_FHIR_URL=https://$EE_HOSTNAME/api/elexisweb/fhir/
      - JEST_AUTH_USERNAME=marco
      - JEST_AUTH_PASSWORD=marco

  elexis-web-calendar-app:
    image: gitlab.medelexis.ch:4567/elexis-web/web-docker/app:develop
    expose: 
      - 3004
    networks:
      - backend
    environment:
      - REACT_APP_API_FHIR_URL=https://$EE_HOSTNAME/api/elexisweb/fhir/
      - REACT_APP_API_URL=https://$EE_HOSTNAME/api/elexisweb/
      - REACT_APP_TITLE=Kalender
      - PUBLIC_URL=/calendar/
      - REACT_APP_AXIOS_LOG=true
      - FULL_WEB=false
      - REACT_APP_ONLY_AGENDA=true
      - REACT_APP_PUSHER_APP_KEY=local
      - REACT_APP_PUSHER_APP_WSPATH=api/elexisweb-socket
      - REACT_APP_PUSHER_APP_WSPORT=80
      - REACT_APP_PUSHER_APP_WSPORT=443
      #######
      - JEST_HEADLESS=true
      - REACT_APP_SITE_URL=https://$EE_HOSTNAME
      - JEST_API_FHIR_URL=https://$EE_HOSTNAME/api/elexisweb/fhir/
      - JEST_AUTH_USERNAME=marco
      - JEST_AUTH_PASSWORD=marco

volumes:
    # for FPM share usage - see web_nextcloud.yml
    elexis-web-api_php: