version: '3'

services:

  # KeyCloak
  # TODO expose only to internal subnet
  keycloak: 
    build: ../keycloak
    expose:
      - 8080
    volumes:
      - ../../site/keycloak-realm.json:/tmp/realm.json:ro
    environment:
      - DB_VENDOR=$RDBMS_TYPE
      - DB_ADDR=$RDBMS_HOST
      - DB_PORT=$RDBMS_PORT
      - DB_DATABASE=$RDBMS_KEYCLOAK_DATABASE
      - DB_USER=$RDBMS_KEYCLOAK_USERNAME
      - DB_PASSWORD=$RDBMS_KEYCLOAK_PASSWORD
      - KEYCLOAK_HOSTNAME=$EE_HOSTNAME
      - KEYCLOAK_USER=KeycloakAdmin # Fallback local admin
      - KEYCLOAK_PASSWORD=$ADMIN_PASSWORD
      - KEYCLOAK_IMPORT=/tmp/realm.json
      - PROXY_ADDRESS_FORWARDING=true