version: '3'

services:

  # KeyCloak
  # https://www.keycloak.org/server/all-config
  # https://www.keycloak.org/server/reverseproxy
  keycloak: 
    image: quay.io/keycloak/keycloak:21.0.2
    networks:
      - backend
    expose:
      - 8080
    command:
      - start
    volumes:
      - ./assets/keycloak/themes/elexis-environment/:/opt/keycloak/themes/elexis-environment/:ro
    environment:
      - KC_DB=$RDBMS_TYPE
      - KC_DB_URL_HOST=$RDBMS_HOST
      - KC_DB_URL_PORT=$RDBMS_PORT
      - KC_DB_URL_DATABASE=$RDBMS_KEYCLOAK_DATABASE
      - KC_DB_URL_PROPERTIES=?$RDBMS_KEYCLOAK_JDBC_PARAMETER_STRING
      - KC_DB_USERNAME=$RDBMS_KEYCLOAK_USERNAME
      - KC_DB_PASSWORD=$RDBMS_KEYCLOAK_PASSWORD
      - KC_HOSTNAME=$EE_HOSTNAME
      - KEYCLOAK_ADMIN=KeycloakAdmin # Fallback local admin
      - KEYCLOAK_ADMIN_PASSWORD=$ADMIN_PASSWORD
      - KC_PROXY=edge
      - KC_HTTP_RELATIVE_PATH=/keycloak/auth
      - KC_HEALTH_ENABLED=true
