version: '3'

services:

  # KeyCloak
  # TODO expose only to internal subnet
  keycloak: 
    build: ../keycloak
    networks:
      - backend
    expose:
      - 8080
    logging:  
      driver: json-file
      options:
          max-size: "2M"
          max-file: "10"    
    #volumes:
      #- ./assets/keycloak/themes/elexis-environment/:/opt/jboss/keycloak/themes/elexis-environment/:ro
    environment:
      - DB_VENDOR=$RDBMS_TYPE
      - DB_ADDR=$RDBMS_HOST
      - DB_PORT=$RDBMS_PORT
      - DB_DATABASE=$RDBMS_KEYCLOAK_DATABASE
      - DB_USER=$RDBMS_KEYCLOAK_USERNAME
      - DB_PASSWORD=$RDBMS_KEYCLOAK_PASSWORD
      - KEYCLOAK_HOSTNAME=$EE_HOSTNAME
      - KEYCLOAK_USER=KeycloakAdmin # Fallback local admin
      - KEYCLOAK_PASSWORD=$ADMIN_PASSWORD
      - PROXY_ADDRESS_FORWARDING=true
      #- KEYCLOAK_DEFAULT_THEME=elexis-environment