version: '3'

services:

  ldap:
    image: osixia/openldap:1.3.0
    command:
      --copy-service --loglevel debug
    volumes:
      - ldap_storage:/var/lib/ldap
      - ldap_configuration:/etc/ldap/slapd.d
      - ./assets/ldap/01-pp.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/01-pp.ldif:ro
      - ./assets/ldap/02-ppolicy.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/02-ppolicy.ldif:ro
      - ./assets/ldap/elexis.schema:/container/service/slapd/assets/config/bootstrap/schema/elexis.schema:ro
      - ../../site/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif:ro
    expose:
      - 389
    environment:
      - LDAP_ORGANISATION=$ORGANISATION_NAME
      - LDAP_DOMAIN=$ORGANSATION_DOMAIN
      - LDAP_READONLY_USER_USERNAME
      - LDAP_READONLY_USER_PASSWORD
      - LDAP_ADMIN_PASSWORD=$ADMIN_PASSWORD
      - LDAP_CONFIG_PASSWORD=$ADMIN_PASSWORD
      - LDAP_TLS=false
      - LDAP_TLS_VERIFY_CLIENT=never
      - LDAP_READONLY_USER=true

volumes:
  ldap_storage:
  ldap_configuration: