version: '3'

services:
    solr:
        image: solr:8.6
        expose:
            - 8983
        networks:
            - backend
        volumes:
            - ./assets/solr/bin/solr-ee-startup:/opt/docker-solr/scripts/solr-ee-startup:ro
            - ./assets/solr/configsets/el-encounters:/opt/solr/server/solr/configsets/el-encounters:ro
            - ./assets/solr/configsets/el-letters:/opt/solr/server/solr/configsets/el-letters:ro
            - ./assets/solr/configsets/el-documents:/opt/solr/server/solr/configsets/el-documents:ro
            - solr_data:/var/solr
        command:
            - solr-ee-startup

volumes:
    solr_data: