version: '3'

services:

  web:
    image: nginx:1.22-alpine
    volumes:
      - ./assets/web/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets/web/etc/conf:/etc/nginx/conf:ro
      - ./assets/web/html-template:/template:ro
      - ./assets/web/html/internal/:/usr/share/nginx/html/internal/:ro
      - ./assets/web/html/external/:/usr/share/nginx/html/external/:ro
      - ./assets/web/html/both/:/usr/share/nginx/html/both/:ro
      - ../../site/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ../../site/certificate.key:/etc/nginx/certificate.key:ro
      - ../../site/certificate.crt:/etc/nginx/certificate.crt:ro
      - ../../site/status.json:/tmp/status.json:ro
    networks:
      - backend
      - myelexis_bridge
    ports:
      - 80:80 #http - redirect to https
      - 443:443 # https
      - 8444:8444 # https - external view
    expose:
      - 8443 # ssl proxy-protocol to wireguard
    depends_on:
      - keycloak
    command: >
      /bin/sh -c "envsubst < /template/eenv.properties.json.template > /usr/share/nginx/html/eenv.properties.json
      && envsubst < /template/elexisweb-env-config.json.template > /usr/share/nginx/html/env-config.json
      && echo "" > /etc/nginx/modules.conf 
      && if [ $ENABLE_ROCKETCHAT  == "true" ]; then echo 'include conf/rocketchat.conf;' >> /etc/nginx/modules.conf; fi
      && if [ $ENABLE_BOOKSTACK == "true" ]; then echo 'include conf/bookstack.conf;' >> /etc/nginx/modules.conf; fi
      && if [ $ENABLE_ELEXIS_SERVER == "true" ]; then echo 'include conf/elexis-server.conf;' >> /etc/nginx/modules.conf; fi
      && if [ $ENABLE_NEXTCLOUD == "true" ]; then echo 'include conf/nextcloud.conf;' >> /etc/nginx/modules.conf; fi
      && if [ $ENABLE_SOLR == "true" ]; then echo 'include conf/solr.conf;' >> /etc/nginx/modules.conf; fi
      && if [ $ENABLE_OCRMYPDF == "true" ]; then echo 'include conf/ocrmypdf.conf;' >> /etc/nginx/modules.conf; fi
      && if [ $ENABLE_ELEXIS_WEB == "true" ]; then echo 'include conf/elexis-web.conf;' >> /etc/nginx/modules.conf; fi
      && echo "" > /etc/nginx/wg_modules.conf
      && if [ $WG_ACCESS_ROCKETCHAT  == *"wg"* ]; then echo 'include conf/rocketchat.conf;' >> /etc/nginx/wg_modules.conf; fi
      && if [ $WG_ACCESS_BOOKSTACK == *"wg"* ]; then echo 'include conf/bookstack.conf;' >> /etc/nginx/wg_modules.conf; fi
      && if [ $WG_ACCESS_ELEXIS_SERVER == *"wg"* ]; then echo 'include conf/elexis-server.conf;' >> /etc/nginx/wg_modules.conf; fi
      && if [ $WG_ACCESS_NEXTCLOUD == *"wg"* ]; then echo 'include conf/nextcloud.conf;' >> /etc/nginx/wg_modules.conf; fi
      && if [ $WG_ACCESS_ELEXIS_WEB == *"wg"* ]; then echo 'include conf/elexis-web.conf;' >> /etc/nginx/wg_modules.conf; fi
      && echo "" > /etc/nginx/ext_modules.conf
      && if [ $WG_ACCESS_ROCKETCHAT  == *"pub"* ]; then echo 'include conf/rocketchat.conf;' >> /etc/nginx/ext_modules.conf; fi
      && if [ $WG_ACCESS_BOOKSTACK == *"pub"* ]; then echo 'include conf/bookstack.conf;' >> /etc/nginx/ext_modules.conf; fi
      && if [ $WG_ACCESS_ELEXIS_SERVER == *"pub"* ]; then echo 'include conf/elexis-server.conf;' >> /etc/nginx/ext_modules.conf; fi
      && if [ $WG_ACCESS_NEXTCLOUD == *"pub"* ]; then echo 'include conf/nextcloud.conf;' >> /etc/nginx/ext_modules.conf; fi
      && if [ $WG_ACCESS_ELEXIS_WEB == *"pub"* ]; then echo 'include conf/elexis-web.conf;' >> /etc/nginx/ext_modules.conf; fi
      && exec nginx -g 'daemon off;'"
    restart: "on-failure" # handle host not found in upstream if not yet ready
    logging:
      driver: "local"
      options:
        max-size: "20m"
        max-file: "10"
        compress: "false"
    environment:
      - EE_HOSTNAME
      - ORGANISATION_NAME
      - ORGANSATION_DOMAIN
      - ENABLE_BOOKSTACK
      - ENABLE_ROCKETCHAT
      - ENABLE_ELEXIS_SERVER
      - ENABLE_NEXTCLOUD
      - ENABLE_SOLR
      - ENABLE_ELEXIS_WEB
      - ENABLE_OCRMYPDF
      - WG_ACCESS_ELEXIS_SERVER
      - WG_ACCESS_BOOKSTACK
      - WG_ACCESS_ROCKETCHAT
      - WG_ACCESS_NEXTCLOUD
      - WG_ACCESS_ELEXIS_WEB

networks:
  backend:
  myelexis_bridge: