version: '3'

services:

  web:
    image: nginx:1.17-alpine
    volumes:
      - ./assets/web/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets/web/etc/conf:/etc/nginx/conf:ro
      - ./assets/web/html-template:/template:ro
      - ./assets/web/html/:/usr/share/nginx/html/public/:ro
      - ../../site/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ../../site/certificate.key:/etc/nginx/certificate.key:ro
      - ../../site/certificate.crt:/etc/nginx/certificate.crt:ro
    ports:
      - 80:80 #http - redirect to https
      - 443:443 # https
      - 636:636 # ldaps
    logging:  
      driver: json-file
      options:
          max-size: "2M"
          max-file: "10"
    depends_on:
      - ldap
      - keycloak
    command: >
      /bin/sh -c "envsubst < /template/eenv.properties.template > /usr/share/nginx/html/eenv.properties 
      && echo "" > /etc/nginx/modules.conf 
      && if [ $ENABLE_ROCKETCHAT  == "true" ]; then echo 'include conf/rocketchat.conf;' >> /etc/nginx/modules.conf; fi
      && if [ $ENABLE_BOOKSTACK == "true" ]; then echo 'include conf/bookstack.conf;' >> /etc/nginx/modules.conf; fi
      && if [ $ENABLE_ELEXIS_SERVER == "true" ]; then echo 'include conf/elexis-server.conf;' >> /etc/nginx/modules.conf; fi
      && exec nginx -g 'daemon off;'"
    restart: "on-failure" # handle host not found in upstream if not yet ready
    environment:
      - EE_VERSION
      - ORGANISATION_NAME
      - ORGANISATION_BASE_DN
      - LDAP_READONLY_USER_USERNAME
      - LDAP_READONLY_USER_PASSWORD
      - ENABLE_BOOKSTACK
      - ENABLE_ROCKETCHAT
      - ENABLE_ELEXIS_SERVER