version: '3'

services:

  web:
    image: nginx:1.22-alpine
    volumes:
      - ./assets/web/web-services-configure.sh:/web-services-configure.sh:ro
      - ./assets/web/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets/web/etc/conf:/etc/nginx/conf:ro
      - ./assets/web/html-template:/template:ro
      - ./assets/web/html/internal/:/usr/share/nginx/html/internal/:ro
      - ./assets/web/html/external/:/usr/share/nginx/html/external/:ro
      - ./assets/web/html/both/:/usr/share/nginx/html/both/:ro
      - ../../site/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ../../site/certificate.key:/etc/nginx/certificate.key:ro
      - ../../site/certificate.crt:/etc/nginx/certificate.crt:ro
      - ../../site/status.json:/tmp/status.json:ro
    networks:
      - backend
      - myelexis_bridge
    ports:
      - 80:80 #http - redirect to https
      - 443:443 # https
    expose:
      - 8443 # to ext (proxy protocoll)
      - 8444 # to wg_services (ssl http2)
    depends_on:
      - keycloak
    command: >
      /bin/sh -c "/web-services-configure.sh && exec nginx -g 'daemon off;'"
    restart: "on-failure" # handle host not found in upstream if not yet ready
    logging:
      driver: "local"
      options:
        max-size: "20m"
        max-file: "10"
        compress: "false"
    environment:
      - EE_HOSTNAME
      - ORGANISATION_NAME
      - ORGANSATION_DOMAIN
      - ENABLE_BOOKSTACK
      - ENABLE_ROCKETCHAT
      - ENABLE_ELEXIS_SERVER
      - ENABLE_NEXTCLOUD
      - ENABLE_SOLR
      - ENABLE_ELEXIS_WEB
      - ENABLE_OCRMYPDF
      - WG_ACCESS_ELEXIS_SERVER
      - WG_ACCESS_BOOKSTACK
      - WG_ACCESS_ROCKETCHAT
      - WG_ACCESS_NEXTCLOUD
      - WG_ACCESS_ELEXIS_WEB

networks:
  backend:
  myelexis_bridge: