version: '3'

services:
    wireguard:
        build: ../wireguard
        restart: unless-stopped
        volumes:
            - wireguard_conf:/etc/wireguard
            - ../../site/wireguard/:/site/
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        networks:
            - myelexis_bridge
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        environment:
            - WG_SERVER_ENDPOINT
            - WG_SERVER_PUBKEY
            - WG_SERVER_PRESHAREDKEY
            - WG_CLIENT_IP

# healthcheck
volumes:
    wireguard_conf:

networks:
    myelexis_bridge: